[project]
name = "vssr"
version = "0.1.0"
description = "Visual Sequential Schemes Recognition"
authors = [
    { name = "Martin Krawiec, Jan Woliński, Tobiasz Jóźwiak" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "opencv-python",
    "torch"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
